### ISSUE TITLE
updating pages checklist

### ISSUE THREAD

**Issue by joshyam-k** [RhoBott/data_at_reed#85]
1. getting-started
- [x] reed_rstudio_server
- [x] desktop_r
- [x] writing_your_thesis
- [x] writing_up_results
- [x] meet_palmer_penguins

2. loading-data
- [x] from_package
- [x] from_csv
- [x] from_excel
- [x] from_googlesheets
- [x] from_internet

3. wrangling-data
- [x] tidy_data (tidy data principles on the website)
- [x] tidying_example
- [x] restructuring_pivot
- [x] subsetting_data
- [x] creating_new_columns
- [x] summarizing_data
- [x] arranging_rows
- [x] frequency_tables
- [x] combining_data
- [x] text_data
- [x] advanced_wrangling

4. presentation-visualization
- [x] intro_to_data_viz
- [x] scatterplots
- [x] linegraphs
- [x] barplots
- [x] histograms
- [x] boxplots
- [x] informative_readable_graphs
- [x] graph_customization
- [x] extensions_of_ggplot2
- [x] summary_tables

**Comment by zolli22** [comment]
updated 7 of 11 pages in the wrangling data section. will pick up tomorrow.

**Comment by zolli22** [comment]
woohoo!!! closing this, since we are done with updates!
